name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Setup SQLite
        uses: ccorsi/setup-sqlite@v1.0.1
        with:
          sqlite-version: 3.40.0
          sqlite-year: 2022
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - run: pnpm install
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test
